
import * as d from './proxies';

export const DIRECTIVES = [
d.SeAbout,
  d.SeApp,
  d.SeAuthentication,
  d.SeBlock,
  d.SeBlockContent,
  d.SeBlockFooter,
  d.SeBlockHeader,
  d.SeButton,
  d.SeCheckbox,
  d.SeChip,
  d.SeContainer,
  d.SeDialog,
  d.SeDialogContent,
  d.SeDialogFooter,
  d.SeDialogHeader,
  d.SeDivider,
  d.SeDropdown,
  d.SeFab,
  d.SeFormField,
  d.SeHeader,
  d.SeIcon,
  d.SeIconEcostruxure,
  d.SeIconLifeison,
  d.SeIconSchneider,
  d.SeLink,
  d.SeList,
  d.SeListGroup,
  d.SeListItem,
  d.SeLoading,
  d.SeRadio,
  d.SeRadioGroup,
  d.SeSidemenu,
  d.SeSidemenuItem,
  d.SeSlider,
  d.SeSnackbar,
  d.SeTabbar,
  d.SeTooltip,
  d.SeTooltipContent,
  d.SeTooltipFooter,
  d.SeTooltipHeader,
  d.SeVisualLinear,
  d.SeVisualRadial
];
