/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@se/web-ui';


interface SeFiltrationSmartCheckboxProps {
  
  /** Id of the refinement that will be used to find the data in the Root Filter store. */
  refinementId?: Components.SeFiltrationSmartCheckbox["refinementId"]
  
  /** Defines if the checkbox is used in mobile view. */
  isMobile?: Components.SeFiltrationSmartCheckbox["isMobile"]
}

interface SeFiltrationSmartCheckboxEvents {
  
  /** Event that has info about refinement whose state should be changed. Root component listens to it. */
  refinementStateChanged: Parameters<JSX.SeFiltrationSmartCheckbox["onRefinementStateChanged"]>[0]
}

interface SeFiltrationSmartCheckboxSlots {
  default: any
}
  
/* generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let se_filtration_smart_checkbox;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			se_filtration_smart_checkbox = element("se-filtration-smart-checkbox");
			if (default_slot) default_slot.c();
			set_custom_element_data(se_filtration_smart_checkbox, "refinement-id", /*refinementId*/ ctx[0]);
			set_custom_element_data(se_filtration_smart_checkbox, "is-mobile", /*isMobile*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, se_filtration_smart_checkbox, anchor);

			if (default_slot) {
				default_slot.m(se_filtration_smart_checkbox, null);
			}

			/*se_filtration_smart_checkbox_binding*/ ctx[7](se_filtration_smart_checkbox);
			current = true;

			if (!mounted) {
				dispose = listen(se_filtration_smart_checkbox, "refinementStateChanged", /*onEvent*/ ctx[3]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 32)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[5],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[5])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[5], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*refinementId*/ 1) {
				set_custom_element_data(se_filtration_smart_checkbox, "refinement-id", /*refinementId*/ ctx[0]);
			}

			if (!current || dirty & /*isMobile*/ 2) {
				set_custom_element_data(se_filtration_smart_checkbox, "is-mobile", /*isMobile*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(se_filtration_smart_checkbox);
			if (default_slot) default_slot.d(detaching);
			/*se_filtration_smart_checkbox_binding*/ ctx[7](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { refinementId } = $$props;
	let { isMobile = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function se_filtration_smart_checkbox_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('refinementId' in $$props) $$invalidate(0, refinementId = $$props.refinementId);
		if ('isMobile' in $$props) $$invalidate(1, isMobile = $$props.isMobile);
		if ('$$scope' in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		refinementId,
		isMobile,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		se_filtration_smart_checkbox_binding
	];
}

class SeFiltrationSmartCheckbox extends SvelteComponent {
  $$prop_def: SeFiltrationSmartCheckboxProps;
  $$events_def: SeFiltrationSmartCheckboxEvents;
  $$slot_def: SeFiltrationSmartCheckboxSlots;

  $on<K extends keyof SeFiltrationSmartCheckboxEvents>(type: K, callback: (e: SeFiltrationSmartCheckboxEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SeFiltrationSmartCheckboxProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			refinementId: 0,
			isMobile: 1,
			getWebComponent: 4
		});
	}

	get refinementId() {
		return this.$$.ctx[0];
	}

	set refinementId(refinementId) {
		this.$$set({ refinementId });
		flush();
	}

	get isMobile() {
		return this.$$.ctx[1];
	}

	set isMobile(isMobile) {
		this.$$set({ isMobile });
		flush();
	}

	get getWebComponent(): HTMLSeFiltrationSmartCheckboxElement | undefined {
		return this.$$.ctx[4];
	}
}

export default SeFiltrationSmartCheckbox;