/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@se/web-ui';


interface SeListItemProps {
  
  /** Defines the title of the item. */
  item?: Components.SeListItem["item"]
  
  /** Defines the description of the item, placed under its title. */
  description?: Components.SeListItem["description"]
  
  /** Defines if the list element should be selected or not. */
  selected?: Components.SeListItem["selected"]
  
  /** Disable the item for any interaction. */
  disabled?: Components.SeListItem["disabled"]
  
  /** Places an icon on the left side of the item list. */
  icon?: Components.SeListItem["icon"]
  
  /** Optional property to define the color of the icon. The default color will be inherited from it's parent. */
  iconColor?: Components.SeListItem["iconColor"]
  
  /** Determines if se-item configures an `a` tag with an `href` attibute.
Default when href is blank configures as a `button` tag. */
  href?: Components.SeListItem["href"]
}

interface SeListItemEvents {
  
  /** Event emitted to notify the list-group component that the selected state has changed. */
  didSelectedChange: Parameters<JSX.SeListItem["onDidSelectedChange"]>[0]
}

interface SeListItemSlots {
  default: any
}
  
/* generated by Svelte v3.44.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let se_list_item;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[14].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[13], null);

	return {
		c() {
			se_list_item = element("se-list-item");
			if (default_slot) default_slot.c();
			set_custom_element_data(se_list_item, "item", /*item*/ ctx[0]);
			set_custom_element_data(se_list_item, "description", /*description*/ ctx[1]);
			set_custom_element_data(se_list_item, "selected", /*selected*/ ctx[2]);
			set_custom_element_data(se_list_item, "disabled", /*disabled*/ ctx[3]);
			set_custom_element_data(se_list_item, "icon", /*icon*/ ctx[4]);
			set_custom_element_data(se_list_item, "icon-color", /*iconColor*/ ctx[5]);
			set_custom_element_data(se_list_item, "href", /*href*/ ctx[6]);
		},
		m(target, anchor) {
			insert(target, se_list_item, anchor);

			if (default_slot) {
				default_slot.m(se_list_item, null);
			}

			/*se_list_item_binding*/ ctx[15](se_list_item);
			current = true;

			if (!mounted) {
				dispose = listen(se_list_item, "didSelectedChange", /*onEvent*/ ctx[8]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 8192)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[13],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[13])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[13], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*item*/ 1) {
				set_custom_element_data(se_list_item, "item", /*item*/ ctx[0]);
			}

			if (!current || dirty & /*description*/ 2) {
				set_custom_element_data(se_list_item, "description", /*description*/ ctx[1]);
			}

			if (!current || dirty & /*selected*/ 4) {
				set_custom_element_data(se_list_item, "selected", /*selected*/ ctx[2]);
			}

			if (!current || dirty & /*disabled*/ 8) {
				set_custom_element_data(se_list_item, "disabled", /*disabled*/ ctx[3]);
			}

			if (!current || dirty & /*icon*/ 16) {
				set_custom_element_data(se_list_item, "icon", /*icon*/ ctx[4]);
			}

			if (!current || dirty & /*iconColor*/ 32) {
				set_custom_element_data(se_list_item, "icon-color", /*iconColor*/ ctx[5]);
			}

			if (!current || dirty & /*href*/ 64) {
				set_custom_element_data(se_list_item, "href", /*href*/ ctx[6]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(se_list_item);
			if (default_slot) default_slot.d(detaching);
			/*se_list_item_binding*/ ctx[15](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { item = undefined } = $$props;
	let { description = undefined } = $$props;
	let { selected = undefined } = $$props;
	let { disabled = undefined } = $$props;
	let { icon = undefined } = $$props;
	let { iconColor = undefined } = $$props;
	let { href = undefined } = $$props;
	const focusElement = (...args) => __ref.focusElement(...args);
	const blurElement = (...args) => __ref.blurElement(...args);
	const setOption = (...args) => __ref.setOption(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(7, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function se_list_item_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(7, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('item' in $$props) $$invalidate(0, item = $$props.item);
		if ('description' in $$props) $$invalidate(1, description = $$props.description);
		if ('selected' in $$props) $$invalidate(2, selected = $$props.selected);
		if ('disabled' in $$props) $$invalidate(3, disabled = $$props.disabled);
		if ('icon' in $$props) $$invalidate(4, icon = $$props.icon);
		if ('iconColor' in $$props) $$invalidate(5, iconColor = $$props.iconColor);
		if ('href' in $$props) $$invalidate(6, href = $$props.href);
		if ('$$scope' in $$props) $$invalidate(13, $$scope = $$props.$$scope);
	};

	return [
		item,
		description,
		selected,
		disabled,
		icon,
		iconColor,
		href,
		__ref,
		onEvent,
		focusElement,
		blurElement,
		setOption,
		getWebComponent,
		$$scope,
		slots,
		se_list_item_binding
	];
}

class SeListItem extends SvelteComponent {
  $$prop_def: SeListItemProps;
  $$events_def: SeListItemEvents;
  $$slot_def: SeListItemSlots;

  $on<K extends keyof SeListItemEvents>(type: K, callback: (e: SeListItemEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SeListItemProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			item: 0,
			description: 1,
			selected: 2,
			disabled: 3,
			icon: 4,
			iconColor: 5,
			href: 6,
			focusElement: 9,
			blurElement: 10,
			setOption: 11,
			getWebComponent: 12
		});
	}

	get item() {
		return this.$$.ctx[0];
	}

	set item(item) {
		this.$$set({ item });
		flush();
	}

	get description() {
		return this.$$.ctx[1];
	}

	set description(description) {
		this.$$set({ description });
		flush();
	}

	get selected() {
		return this.$$.ctx[2];
	}

	set selected(selected) {
		this.$$set({ selected });
		flush();
	}

	get disabled() {
		return this.$$.ctx[3];
	}

	set disabled(disabled) {
		this.$$set({ disabled });
		flush();
	}

	get icon() {
		return this.$$.ctx[4];
	}

	set icon(icon) {
		this.$$set({ icon });
		flush();
	}

	get iconColor() {
		return this.$$.ctx[5];
	}

	set iconColor(iconColor) {
		this.$$set({ iconColor });
		flush();
	}

	get href() {
		return this.$$.ctx[6];
	}

	set href(href) {
		this.$$set({ href });
		flush();
	}

	
  /**  */
 get focusElement(): Components.SeListItem["focusElement"] {
		return this.$$.ctx[9];
	}

	
  /**  */
 get blurElement(): Components.SeListItem["blurElement"] {
		return this.$$.ctx[10];
	}

	
  /**  */
 get setOption(): Components.SeListItem["setOption"] {
		return this.$$.ctx[11];
	}

	get getWebComponent(): HTMLSeListItemElement | undefined {
		return this.$$.ctx[12];
	}
}

export default SeListItem;