/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@se/web-ui';


interface SeStepperProps {
  
  /** Sets the background color of your stepper.
The default setting is `primary`, implementing a green background for the stepper visual items.
The `alternative` setting implements a white background for the stepper visual items. This setting is best used against a gray background. */
  color?: Components.SeStepper["color"]
  
  /** Defines if the stepper items must be completed sequentially.
The default setting is `true`, each stepper item must be validated before advancing to the next step.
`false` allows each step to be selected in any order. */
  linear?: Components.SeStepper["linear"]
  
  /** Defines if the stepper takes the whole space. */
  block?: Components.SeStepper["block"]
  
  /** Defines if the stepper items is interactive or not.
The default setting is `true`, each stepper item can be interacted with. `linear` keeps its same interaction limitation.
`false` disabled the interactivness. It overrides the individual stepper item `interactive` property. */
  interactive?: Components.SeStepper["interactive"]
  
  /** Sets the max width for each stepper label
The default setting is `none`. */
  labelMaxWidth?: Components.SeStepper["labelMaxWidth"]
}

interface SeStepperEvents {
  
  /** Event to send to the parent component when a stepper item is clicked and next and previous will be clicked.
The Stepper Item data is passed to the parent. */
  didChange: Parameters<JSX.SeStepper["onDidChange"]>[0]
}

interface SeStepperSlots {
  default: any
}
  
/* generated by Svelte v3.44.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let se_stepper;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[12].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[11], null);

	return {
		c() {
			se_stepper = element("se-stepper");
			if (default_slot) default_slot.c();
			set_custom_element_data(se_stepper, "color", /*color*/ ctx[0]);
			set_custom_element_data(se_stepper, "linear", /*linear*/ ctx[1]);
			set_custom_element_data(se_stepper, "block", /*block*/ ctx[2]);
			set_custom_element_data(se_stepper, "interactive", /*interactive*/ ctx[3]);
			set_custom_element_data(se_stepper, "label-max-width", /*labelMaxWidth*/ ctx[4]);
		},
		m(target, anchor) {
			insert(target, se_stepper, anchor);

			if (default_slot) {
				default_slot.m(se_stepper, null);
			}

			/*se_stepper_binding*/ ctx[13](se_stepper);
			current = true;

			if (!mounted) {
				dispose = listen(se_stepper, "didChange", /*onEvent*/ ctx[6]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 2048)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[11],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[11])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[11], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*color*/ 1) {
				set_custom_element_data(se_stepper, "color", /*color*/ ctx[0]);
			}

			if (!current || dirty & /*linear*/ 2) {
				set_custom_element_data(se_stepper, "linear", /*linear*/ ctx[1]);
			}

			if (!current || dirty & /*block*/ 4) {
				set_custom_element_data(se_stepper, "block", /*block*/ ctx[2]);
			}

			if (!current || dirty & /*interactive*/ 8) {
				set_custom_element_data(se_stepper, "interactive", /*interactive*/ ctx[3]);
			}

			if (!current || dirty & /*labelMaxWidth*/ 16) {
				set_custom_element_data(se_stepper, "label-max-width", /*labelMaxWidth*/ ctx[4]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(se_stepper);
			if (default_slot) default_slot.d(detaching);
			/*se_stepper_binding*/ ctx[13](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { color = undefined } = $$props;
	let { linear = undefined } = $$props;
	let { block = undefined } = $$props;
	let { interactive = undefined } = $$props;
	let { labelMaxWidth = undefined } = $$props;
	const reset = (...args) => __ref.reset(...args);
	const previous = (...args) => __ref.previous(...args);
	const next = (...args) => __ref.next(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(5, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function se_stepper_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(5, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('color' in $$props) $$invalidate(0, color = $$props.color);
		if ('linear' in $$props) $$invalidate(1, linear = $$props.linear);
		if ('block' in $$props) $$invalidate(2, block = $$props.block);
		if ('interactive' in $$props) $$invalidate(3, interactive = $$props.interactive);
		if ('labelMaxWidth' in $$props) $$invalidate(4, labelMaxWidth = $$props.labelMaxWidth);
		if ('$$scope' in $$props) $$invalidate(11, $$scope = $$props.$$scope);
	};

	return [
		color,
		linear,
		block,
		interactive,
		labelMaxWidth,
		__ref,
		onEvent,
		reset,
		previous,
		next,
		getWebComponent,
		$$scope,
		slots,
		se_stepper_binding
	];
}

class SeStepper extends SvelteComponent {
  $$prop_def: SeStepperProps;
  $$events_def: SeStepperEvents;
  $$slot_def: SeStepperSlots;

  $on<K extends keyof SeStepperEvents>(type: K, callback: (e: SeStepperEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SeStepperProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			color: 0,
			linear: 1,
			block: 2,
			interactive: 3,
			labelMaxWidth: 4,
			reset: 7,
			previous: 8,
			next: 9,
			getWebComponent: 10
		});
	}

	get color() {
		return this.$$.ctx[0];
	}

	set color(color) {
		this.$$set({ color });
		flush();
	}

	get linear() {
		return this.$$.ctx[1];
	}

	set linear(linear) {
		this.$$set({ linear });
		flush();
	}

	get block() {
		return this.$$.ctx[2];
	}

	set block(block) {
		this.$$set({ block });
		flush();
	}

	get interactive() {
		return this.$$.ctx[3];
	}

	set interactive(interactive) {
		this.$$set({ interactive });
		flush();
	}

	get labelMaxWidth() {
		return this.$$.ctx[4];
	}

	set labelMaxWidth(labelMaxWidth) {
		this.$$set({ labelMaxWidth });
		flush();
	}

	
  /** Call the `reset` method to reset the stepper to the indicated step.  This also invalidates any validated steps.
It no step parameter is provided, it will reset to the first stepper item. */
 get reset(): Components.SeStepper["reset"] {
		return this.$$.ctx[7];
	}

	
  /** Call the `previous` method to navigate to the previous step from the step that is currently selected. */
 get previous(): Components.SeStepper["previous"] {
		return this.$$.ctx[8];
	}

	
  /** Call the `next` method to navigate to the next step from the step that is currently selected.
This will not work in linear mode if the next step is not validated. */
 get next(): Components.SeStepper["next"] {
		return this.$$.ctx[9];
	}

	get getWebComponent(): HTMLSeStepperElement | undefined {
		return this.$$.ctx[10];
	}
}

export default SeStepper;