/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SeApp {}
  interface SeAppAttributes extends StencilHTMLAttributes {}

  interface SeButton {
    /**
    * Optional property that defines the background color of the button. `primary` is a green color. `accent` is a blue color. `warn` is an orange color. `error` is a red color.
    */
    'color': 'primary' | 'accent' | 'warn' | 'error';
    /**
    * Optional property that defines if the button is disabled.  Set to `false` by default.
    */
    'disabled': boolean;
    /**
    * Optional property that determines if your button includes an icon.
    */
    'icon': string;
    /**
    * Defines the visual appearance of the button. `flat` is the default mode, which includes a gray background. `raised` adds a box shadow to the button. `outline` adds a border to the button. `text` mode has no border or background color. `login` and `signup` modes are specific for "Login" and "Sign Up" buttons in your application.
    */
    'mode': 'flat' | 'raised' | 'outline' | 'text' | 'login' | 'signup';
    /**
    * Set a selected button from the parent component.
    */
    'setActive': (val: boolean) => void;
    /**
    * Set a color for your button from the parent component.
    */
    'setColor': (val: "primary" | "accent" | "warn" | "error") => void;
    /**
    * Set the disabled property for your button from the parent component.
    */
    'setDisabled': (val: boolean) => void;
    /**
    * Indicate if the button is part of a group of buttons within the `se-buttons` component.
    */
    'setGrouped': () => void;
    /**
    * Optional property that defines the value of your button, which gets passed to the parent component when clicking the button.
    */
    'value': string;
  }
  interface SeButtonAttributes extends StencilHTMLAttributes {
    /**
    * Optional property that defines the background color of the button. `primary` is a green color. `accent` is a blue color. `warn` is an orange color. `error` is a red color.
    */
    'color'?: 'primary' | 'accent' | 'warn' | 'error';
    /**
    * Optional property that defines if the button is disabled.  Set to `false` by default.
    */
    'disabled'?: boolean;
    /**
    * Optional property that determines if your button includes an icon.
    */
    'icon'?: string;
    /**
    * Defines the visual appearance of the button. `flat` is the default mode, which includes a gray background. `raised` adds a box shadow to the button. `outline` adds a border to the button. `text` mode has no border or background color. `login` and `signup` modes are specific for "Login" and "Sign Up" buttons in your application.
    */
    'mode'?: 'flat' | 'raised' | 'outline' | 'text' | 'login' | 'signup';
    /**
    * Passes button data to the parent component on a click.
    */
    'onClicked'?: (event: CustomEvent<any>) => void;
    /**
    * Optional property that defines the value of your button, which gets passed to the parent component when clicking the button.
    */
    'value'?: string;
  }

  interface SeButtons {
    /**
    * Optional property that defines the background color of each button in the group. `primary` is a green color. `accent` is a blue color. `warn` is an orange color. `error` is a red color.
    */
    'color': 'primary' | 'accent' | 'warn' | 'error';
    /**
    * Optional property that defines if the button is disabled.  Set to `false` by default.
    */
    'disabled': boolean;
    /**
    * Defines the functionality of your button group. `checkbox` is the default option, where all buttons in the group can be selected. `radio` mode indicates that only one button in the group can be selected at a time.
    */
    'mode': 'checkbox' | 'radio';
  }
  interface SeButtonsAttributes extends StencilHTMLAttributes {
    /**
    * Optional property that defines the background color of each button in the group. `primary` is a green color. `accent` is a blue color. `warn` is an orange color. `error` is a red color.
    */
    'color'?: 'primary' | 'accent' | 'warn' | 'error';
    /**
    * Optional property that defines if the button is disabled.  Set to `false` by default.
    */
    'disabled'?: boolean;
    /**
    * Defines the functionality of your button group. `checkbox` is the default option, where all buttons in the group can be selected. `radio` mode indicates that only one button in the group can be selected at a time.
    */
    'mode'?: 'checkbox' | 'radio';
    /**
    * Passes the selected button value to the parent component when clicking on a button in the group.
    */
    'onChange'?: (event: CustomEvent) => void;
  }

  interface SeContainer {
    /**
    * Defines the inner apparance of a container. `widget` Add a small spacing all around the container so all widgets are spaced with the same distance. `fill` Default. Take the full space of the container. `centered` center the container so the content does no exceed a max width.
    */
    'mode': 'widget' | 'fill' | 'centered' | 'card';
    /**
    * In specific case, it can be necessary to define the container with an absolute position (inside an angular router-container ). Most of the time, the default position will work perfectly with flex box. `relative` Default. Perfect to use with flex content. `absolute` Help in specific cases. Make sure you know that you are doing.
    */
    'position': 'relative' | 'absolute';
  }
  interface SeContainerAttributes extends StencilHTMLAttributes {
    /**
    * Defines the inner apparance of a container. `widget` Add a small spacing all around the container so all widgets are spaced with the same distance. `fill` Default. Take the full space of the container. `centered` center the container so the content does no exceed a max width.
    */
    'mode'?: 'widget' | 'fill' | 'centered' | 'card';
    /**
    * In specific case, it can be necessary to define the container with an absolute position (inside an angular router-container ). Most of the time, the default position will work perfectly with flex box. `relative` Default. Perfect to use with flex content. `absolute` Help in specific cases. Make sure you know that you are doing.
    */
    'position'?: 'relative' | 'absolute';
  }

  interface SeDivider {
    'mode': "horizontal" | "vertical" | "inset";
  }
  interface SeDividerAttributes extends StencilHTMLAttributes {
    'mode'?: "horizontal" | "vertical" | "inset";
  }

  interface SeHeader {
    /**
    * Title of the application
    */
    'appTitle': string;
  }
  interface SeHeaderAttributes extends StencilHTMLAttributes {
    /**
    * Title of the application
    */
    'appTitle'?: string;
  }

  interface SeIconSchneider {}
  interface SeIconSchneiderAttributes extends StencilHTMLAttributes {}

  interface SeNavbar {
    'color': 'primary' | 'secondary' | 'tab';
  }
  interface SeNavbarAttributes extends StencilHTMLAttributes {
    'color'?: 'primary' | 'secondary' | 'tab';
  }

  interface SeRadioOnOff {
    /**
    * Optional property that defines if the radio on/off switch is disabled.  Set to `false` by default.
    */
    'disabled': boolean;
    /**
    * Defines the visual appearance of the on/off radio switch. `default` is the default mode. Use `header` if the on/off radio switch is within a header element to reduce its visual height.
    */
    'mode': 'default' | 'header';
    /**
    * Defines the text the user will see for the "off" or "inactive" part of the radio switch.
    */
    'textOff': string;
    /**
    * Defines the text the user will see for the "on" or "active" part of the radio switch.
    */
    'textOn': string;
  }
  interface SeRadioOnOffAttributes extends StencilHTMLAttributes {
    /**
    * Optional property that defines if the radio on/off switch is disabled.  Set to `false` by default.
    */
    'disabled'?: boolean;
    /**
    * Defines the visual appearance of the on/off radio switch. `default` is the default mode. Use `header` if the on/off radio switch is within a header element to reduce its visual height.
    */
    'mode'?: 'default' | 'header';
    /**
    * Passes the current state (true or false) to the parent component when clicking on a button in the group.
    */
    'onChange'?: (event: CustomEvent<any>) => void;
    /**
    * Defines the text the user will see for the "off" or "inactive" part of the radio switch.
    */
    'textOff'?: string;
    /**
    * Defines the text the user will see for the "on" or "active" part of the radio switch.
    */
    'textOn'?: string;
  }

  interface SeSidenavItem {
    'itemTitle': string;
  }
  interface SeSidenavItemAttributes extends StencilHTMLAttributes {
    'itemTitle'?: string;
  }

  interface SeSidenav {
    'toggle': () => void;
  }
  interface SeSidenavAttributes extends StencilHTMLAttributes {}

  interface SeWidgetContent {
    'mode': 'fill';
  }
  interface SeWidgetContentAttributes extends StencilHTMLAttributes {
    'mode'?: 'fill';
  }

  interface SeWidgetFooter {}
  interface SeWidgetFooterAttributes extends StencilHTMLAttributes {}

  interface SeWidgetHeader {}
  interface SeWidgetHeaderAttributes extends StencilHTMLAttributes {}

  interface SeWidget {}
  interface SeWidgetAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SeApp': Components.SeApp;
    'SeButton': Components.SeButton;
    'SeButtons': Components.SeButtons;
    'SeContainer': Components.SeContainer;
    'SeDivider': Components.SeDivider;
    'SeHeader': Components.SeHeader;
    'SeIconSchneider': Components.SeIconSchneider;
    'SeNavbar': Components.SeNavbar;
    'SeRadioOnOff': Components.SeRadioOnOff;
    'SeSidenavItem': Components.SeSidenavItem;
    'SeSidenav': Components.SeSidenav;
    'SeWidgetContent': Components.SeWidgetContent;
    'SeWidgetFooter': Components.SeWidgetFooter;
    'SeWidgetHeader': Components.SeWidgetHeader;
    'SeWidget': Components.SeWidget;
  }

  interface StencilIntrinsicElements {
    'se-app': Components.SeAppAttributes;
    'se-button': Components.SeButtonAttributes;
    'se-buttons': Components.SeButtonsAttributes;
    'se-container': Components.SeContainerAttributes;
    'se-divider': Components.SeDividerAttributes;
    'se-header': Components.SeHeaderAttributes;
    'se-icon-schneider': Components.SeIconSchneiderAttributes;
    'se-navbar': Components.SeNavbarAttributes;
    'se-radio-on-off': Components.SeRadioOnOffAttributes;
    'se-sidenav-item': Components.SeSidenavItemAttributes;
    'se-sidenav': Components.SeSidenavAttributes;
    'se-widget-content': Components.SeWidgetContentAttributes;
    'se-widget-footer': Components.SeWidgetFooterAttributes;
    'se-widget-header': Components.SeWidgetHeaderAttributes;
    'se-widget': Components.SeWidgetAttributes;
  }


  interface HTMLSeAppElement extends Components.SeApp, HTMLStencilElement {}
  var HTMLSeAppElement: {
    prototype: HTMLSeAppElement;
    new (): HTMLSeAppElement;
  };

  interface HTMLSeButtonElement extends Components.SeButton, HTMLStencilElement {}
  var HTMLSeButtonElement: {
    prototype: HTMLSeButtonElement;
    new (): HTMLSeButtonElement;
  };

  interface HTMLSeButtonsElement extends Components.SeButtons, HTMLStencilElement {}
  var HTMLSeButtonsElement: {
    prototype: HTMLSeButtonsElement;
    new (): HTMLSeButtonsElement;
  };

  interface HTMLSeContainerElement extends Components.SeContainer, HTMLStencilElement {}
  var HTMLSeContainerElement: {
    prototype: HTMLSeContainerElement;
    new (): HTMLSeContainerElement;
  };

  interface HTMLSeDividerElement extends Components.SeDivider, HTMLStencilElement {}
  var HTMLSeDividerElement: {
    prototype: HTMLSeDividerElement;
    new (): HTMLSeDividerElement;
  };

  interface HTMLSeHeaderElement extends Components.SeHeader, HTMLStencilElement {}
  var HTMLSeHeaderElement: {
    prototype: HTMLSeHeaderElement;
    new (): HTMLSeHeaderElement;
  };

  interface HTMLSeIconSchneiderElement extends Components.SeIconSchneider, HTMLStencilElement {}
  var HTMLSeIconSchneiderElement: {
    prototype: HTMLSeIconSchneiderElement;
    new (): HTMLSeIconSchneiderElement;
  };

  interface HTMLSeNavbarElement extends Components.SeNavbar, HTMLStencilElement {}
  var HTMLSeNavbarElement: {
    prototype: HTMLSeNavbarElement;
    new (): HTMLSeNavbarElement;
  };

  interface HTMLSeRadioOnOffElement extends Components.SeRadioOnOff, HTMLStencilElement {}
  var HTMLSeRadioOnOffElement: {
    prototype: HTMLSeRadioOnOffElement;
    new (): HTMLSeRadioOnOffElement;
  };

  interface HTMLSeSidenavItemElement extends Components.SeSidenavItem, HTMLStencilElement {}
  var HTMLSeSidenavItemElement: {
    prototype: HTMLSeSidenavItemElement;
    new (): HTMLSeSidenavItemElement;
  };

  interface HTMLSeSidenavElement extends Components.SeSidenav, HTMLStencilElement {}
  var HTMLSeSidenavElement: {
    prototype: HTMLSeSidenavElement;
    new (): HTMLSeSidenavElement;
  };

  interface HTMLSeWidgetContentElement extends Components.SeWidgetContent, HTMLStencilElement {}
  var HTMLSeWidgetContentElement: {
    prototype: HTMLSeWidgetContentElement;
    new (): HTMLSeWidgetContentElement;
  };

  interface HTMLSeWidgetFooterElement extends Components.SeWidgetFooter, HTMLStencilElement {}
  var HTMLSeWidgetFooterElement: {
    prototype: HTMLSeWidgetFooterElement;
    new (): HTMLSeWidgetFooterElement;
  };

  interface HTMLSeWidgetHeaderElement extends Components.SeWidgetHeader, HTMLStencilElement {}
  var HTMLSeWidgetHeaderElement: {
    prototype: HTMLSeWidgetHeaderElement;
    new (): HTMLSeWidgetHeaderElement;
  };

  interface HTMLSeWidgetElement extends Components.SeWidget, HTMLStencilElement {}
  var HTMLSeWidgetElement: {
    prototype: HTMLSeWidgetElement;
    new (): HTMLSeWidgetElement;
  };

  interface HTMLElementTagNameMap {
    'se-app': HTMLSeAppElement
    'se-button': HTMLSeButtonElement
    'se-buttons': HTMLSeButtonsElement
    'se-container': HTMLSeContainerElement
    'se-divider': HTMLSeDividerElement
    'se-header': HTMLSeHeaderElement
    'se-icon-schneider': HTMLSeIconSchneiderElement
    'se-navbar': HTMLSeNavbarElement
    'se-radio-on-off': HTMLSeRadioOnOffElement
    'se-sidenav-item': HTMLSeSidenavItemElement
    'se-sidenav': HTMLSeSidenavElement
    'se-widget-content': HTMLSeWidgetContentElement
    'se-widget-footer': HTMLSeWidgetFooterElement
    'se-widget-header': HTMLSeWidgetHeaderElement
    'se-widget': HTMLSeWidgetElement
  }

  interface ElementTagNameMap {
    'se-app': HTMLSeAppElement;
    'se-button': HTMLSeButtonElement;
    'se-buttons': HTMLSeButtonsElement;
    'se-container': HTMLSeContainerElement;
    'se-divider': HTMLSeDividerElement;
    'se-header': HTMLSeHeaderElement;
    'se-icon-schneider': HTMLSeIconSchneiderElement;
    'se-navbar': HTMLSeNavbarElement;
    'se-radio-on-off': HTMLSeRadioOnOffElement;
    'se-sidenav-item': HTMLSeSidenavItemElement;
    'se-sidenav': HTMLSeSidenavElement;
    'se-widget-content': HTMLSeWidgetContentElement;
    'se-widget-footer': HTMLSeWidgetFooterElement;
    'se-widget-header': HTMLSeWidgetHeaderElement;
    'se-widget': HTMLSeWidgetElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
